services:
  - type: web
    name: backend
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./backend/Dockerfile
    buildCommand: "" # karena udah ditangani Dockerfile
    startCommand: "" # karena sudah di Dockerfile
    envVars:
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        value: your_postgres_url
    autoDeploy: true

  - type: web
    name: frontend
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    buildCommand: "" # handled by Dockerfile
    startCommand: "" # handled by Dockerfile
    envVars:
      - key: PORT
        value: 5001
      - key: VITE_BACKEND_URL
        value: https://backend-cjif.onrender.com # ganti setelah backend live
    autoDeploy: true
