services:
  - type: web
    name: backend
    env: node
    repo: https://github.com/novikhasiregar/testing-devops
    region: oregon
    plan: free
    branch: devs
    rootDir: ./backend
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: PORT
        value: 5000

  - type: web
    name: frontend
    env: node
    repo: https://github.com/novikhasiregar/testing-devops
    region: oregon
    plan: free
    branch: devs
    rootDir: ./frontend
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: PORT
        value: 5001
      - key: VITE_BACKEND_URL
        value: https://backend-<username>.onrender.com # Ganti sesuai nama app backend di render nanti
